AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_function/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Environment:
        Variables:
          SECRET_SERVICE_BASE_URL: ""
          SECRET_NAME: ""
      Events:
        CalendarAPI:
          Type: Api
          Properties:
            Path: /calendar-data
            Method: GET
