name: PR Checks

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    # Set up Python
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install Node.js (to enable npx)
    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version: '18'

    # Install ESLint and Stylelint dependencies
    - name: Install Node.js Dependencies for Linting
      run: |
        npm install eslint stylelint stylelint-config-standard --save-dev

    # Run ESLint for JS files
    - name: Run ESLint on JavaScript Files
      run: |
        npx eslint calendar_frontend/lodgify-calendar.js --max-warnings 0


    # Run Stylelint for CSS files
    - name: Run Stylelint on CSS Files
      run: |
        npx stylelint "calendar_frontend/**/*.css" --max-warnings 0


    # Run pylint
    - name: Run Pylint
      run: |
        pylint lambda_function --fail-under=7

    # Run pytest with coverage
    - name: Run Pytest with coverage
      run: |
        pytest --cov=lambda_function --cov-fail-under=5 tests

    # Run SAM build
    - name: Build SAM Project
      run: |
        sam build --use-container --parameter-overrides Architecture=x86_64
